In [1]:
!python -m pip install numpy

In [2]:
import numpy as np

In [3]:
num_list = [1, 2, 3, 4]
int_arr2 = np.array(num_list)
print(int_arr2)

[1 2 3 4]


In [4]:
arr1 = np.arange(0, 10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [5]:
arr2 = np.arange(0, 10, 2)
arr2

array([0, 2, 4, 6, 8])

In [ ]:
arr2 = np.arange(0, 10, 2)
arr2

In [6]:
arr3 = np.arange(5)
arr3

array([0, 1, 2, 3, 4])

In [7]:
list_data1 = [1, '2', 3]
arr4 = np.array(list_data1)
arr4

array(['1', '2', '3'], dtype='<U21')

In [8]:
list_data2 = [1, 2., 3]
arr5 = np.array(list_data2)
arr5

array([1., 2., 3.])

In [9]:
temp6 = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr6 = np.array(temp6)
print(arr6)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
print(temp6)

[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]


In [11]:
print(type(temp6))
print(type(arr6))

<class 'list'>
<class 'numpy.ndarray'>


In [12]:
arr7 = np.array([
                    [[1, 2, 3, 4], [5, 6 , 7, 8]],
                    [[9, 10, 11, 12], [13, 14 , 15, 16]],
                    [[17, 18, 19, 20], [21, 22, 23, 24]]
                 ])
print(arr7)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[ 9 10 11 12]
  [13 14 15 16]]

 [[17 18 19 20]
  [21 22 23 24]]]


In [18]:
arr8 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

print(arr8.ndim)
print(arr8.shape)

arr9 = arr8.reshape(2, 5)

print(arr9.ndim)
print(arr9.shape)

1
(10,)
2
(2, 5)


In [19]:
print(arr8)

[ 1  2  3  4  5  6  7  8  9 10]


In [20]:
print(arr9)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [21]:
arr8.reshape(3, 3)

ValueError: cannot reshape array of size 10 into shape (3,3)

In [ ]:
arr10 = arr8.reshape(2, 5, 1)

print(arr10.ndim)
print(arr10.shape)
print(arr10)

# (2, 5) 의 shape
# [[ 1  2  3  4  5]
#  [ 6  7  8  9 10]]

3
(2, 5, 1)
[[[ 1]
  [ 2]
  [ 3]
  [ 4]
  [ 5]]

 [[ 6]
  [ 7]
  [ 8]
  [ 9]
  [10]]]


# Shape

(2, 5) 와 (2, 5, 1) 은 전혀 다른 numpy array 이다.  
(10, ) 와 (10, 1) 은 전혀 다른 numpy array 이다.

In [23]:
arr11 = np.linspace(1, 10, 10)

print(arr11)
print(arr11.dtype)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]
float64


In [24]:
arr12 = np.linspace(1, 10, 10, dtype=int)

print(arr12)
print(arr12.dtype)

[ 1  2  3  4  5  6  7  8  9 10]
int64


In [26]:
arr13 = np.linspace(0, 10, 10)

print(arr13)
print(arr13.dtype)

[ 0.          1.11111111  2.22222222  3.33333333  4.44444444  5.55555556
  6.66666667  7.77777778  8.88888889 10.        ]
float64


In [28]:
arr14 = np.zeros(10)
print(arr14)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


In [30]:
data1 = list(range(0, 10))

data2 = []
for x in data1:
    data2.append(x*2)

data3 = [x*2 for x in data1]

print(data1)
print(data2)
print(data3)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]
[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [33]:
data4 = np.array(data1)
data5 = 2 * data4
print(data5)

[ 0  2  4  6  8 10 12 14 16 18]


In [34]:
data5.dtype

dtype('int64')

In [35]:
a = np.array([1, 2, 3])
b = np.array([10, 20, 30])

print(2 * a + b)
print(a == 2)
print(b > 10)
print((a == 2) & (b > 10))

[12 24 36]
[False  True False]
[False  True  True]
[False  True False]


In [36]:
c = np.array([[0, 1, 2], [3, 4, 5]])
d = np.array([
                [
                    [1, 2, 3, 4],
                    [5, 6, 7, 8],
                    [9, 10, 11, 12]
                 ],
                [
                    [11, 12, 13, 14],
                    [15, 16, 17, 18],
                    [19, 20, 21, 22]
                 ]
             ])

In [41]:
print(c.ndim, c.shape, c.size)
print(c)

2 (2, 3) 6
[[0 1 2]
 [3 4 5]]


In [42]:
print(d.ndim, d.shape, d.size)
print(d)

3 (2, 3, 4) 24
[[[ 1  2  3  4]
  [ 5  6  7  8]
  [ 9 10 11 12]]

 [[11 12 13 14]
  [15 16 17 18]
  [19 20 21 22]]]


In [44]:
f = np.array([10, 11, 12, 13, 14])
print(f[2])
print(f[-1])

12
14


In [45]:
g = np.array([[0, 1, 2], [3, 4, 5]])
print(g)

[[0 1 2]
 [3 4 5]]


In [46]:
g[0]

array([0, 1, 2])

In [49]:
print(g[0][0], g[0][1])

0 1


In [50]:
print(g[1][-1])

5


In [51]:
print(g[0, 1])

1


In [52]:
# [[0 1 2]
#  [3 4 5]]

# g[?, ?] = g[?][?]
print(g[:, 1])

[1 4]


In [53]:
h = np.array([[0, 1, 2, 3], [4, 5, 6, 7]])
print(h[:, 1])

[1 5]


In [55]:
(h[:, 1]).shape

(2,)

In [57]:
print(h[1, 1:4])

[5 6 7]


In [58]:
print(h[:, :2])

[[0 1]
 [4 5]]


In [59]:
i = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
ix = np.array([True, False, True, False, True,
               False, True, False, True, False])
i[ix]

array([0, 2, 4, 6, 8])

In [60]:
temp7 = i % 2 == 0
print(temp7.shape)
print(temp7)

(10,)
[ True False  True False  True False  True False  True False]


In [61]:
i[temp7]

array([0, 2, 4, 6, 8])

In [62]:
i[i % 2 == 0]

array([0, 2, 4, 6, 8])

In [63]:
j = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
print(j[:, [0, 3]])

[[ 1  4]
 [ 5  8]
 [ 9 12]]


In [64]:
j % 4 == 0

array([[False, False, False,  True],
       [False, False, False,  True],
       [False, False, False,  True]])

In [65]:
j % 4 == 1

array([[ True, False, False, False],
       [ True, False, False, False],
       [ True, False, False, False]])

In [66]:
(j % 4 == 0) | (j % 4 == 1)

array([[ True, False, False,  True],
       [ True, False, False,  True],
       [ True, False, False,  True]])

In [67]:
j[(j % 4 == 0) | (j % 4 == 1)]

array([ 1,  4,  5,  8,  9, 12])

In [69]:
j[[2, 0, 1]]

array([[ 9, 10, 11, 12],
       [ 1,  2,  3,  4],
       [ 5,  6,  7,  8]])

In [ ]:
k = np.array(range(1, 21))
print(k)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [73]:
k[k % 3 == 0]

array([ 3,  6,  9, 12, 15, 18])

In [74]:
k[k % 4 == 1]

array([ 1,  5,  9, 13, 17])

In [75]:
k[(k % 3 == 0) & (k % 4 == 1)]

array([9])